# Generated by Django 3.0.3 on 2020-02-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(choices=[(1, 'Type one'), (2, 'Type two'), (3, 'Type three'), (4, 'Type four')], verbose_name='Task type')),
                ('tast_desc', models.CharField(max_length=200, verbose_name='Task description')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskTrackerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(choices=[(1, 'Type one'), (2, 'Type two'), (3, 'Type three'), (4, 'Type four')], verbose_name='Task type')),
                ('update_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=15, verbose_name='Task update type')),
            ],
            options={
                'verbose_name': 'Task Tracker',
                'verbose_name_plural': 'Task Trackers',
            },
        ),
    ]
