# Generated by Django 3.0.3 on 2020-02-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskreminder', '0002_auto_20200209_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktrackermodel',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=40, verbose_name='Email address'),
        ),
    ]
