# Generated by Django 3.0.3 on 2020-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskreminder', '0003_tasktrackermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktrackermodel',
            name='email',
            field=models.CharField(max_length=40, unique=True, verbose_name='Email address'),
        ),
    ]
